In [1]:
import pandas as pd
import numpy as np

df=pd.read_csv("retail_sales_rawdata.csv")

In [2]:
df.describe(include='all')

,Order_ID,Customer_ID,Order_Date,Region,City,Sales_Channel,Customer_Segment,Age,Category,Subcategory,Quantity,Unit_Price,Total_Sales,Cost,Profit,Payment_Method,Satisfaction,Delivery_Date
count,10000,10000,9966,9754,9654,9709,9761,9960,9803,9646,9952.000000,9.950000e+03,1.000000e+04,10000.000000,10000.000000,9608,9963,9821
unique,9890,1230,1278,11,15,11,9,105,14,32,NaN,NaN,NaN,NaN,NaN,12,64,1282
top,ORD-9509-007488,CUST_00725,2023-05-05,South,Bengaluru,Online,Consumer,39.0,Grocery,Snacks,NaN,NaN,NaN,NaN,NaN,UPI,5.0,2025-06-14
freq,2,21,19,2118,741,4559,5468,382,1530,408,NaN,NaN,NaN,NaN,NaN,2860,682,21
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.297227,1.592891e+04,7.134601e+04,33579.576209,15919.818089,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.758495,3.516055e+04,6.406160e+05,61209.750719,31581.610015,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.793667e+01,0.000000e+00,12.000000,7.090000,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,1.675697e+03,4.280568e+03,2609.295000,1115.330000,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,6.081235e+03,1.628381e+04,9916.000000,4407.800000,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,2.263057e+04,6.058336e+04,36842.112500,16256.947500,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,999.000000,2.053172e+06,4.490045e+07,719673.390000,449322.220000,NaN,NaN,NaN

In [3]:
df.duplicated(subset='Order_ID').sum()

110

In [4]:
df.drop_duplicates(subset='Order_ID',inplace=True)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9890 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          9890 non-null   object
 1   Customer_ID       9890 non-null   object
 2   Order_Date        9857 non-null   object
 3   Region            9648 non-null   object
 4   City              9547 non-null   object
 5   Sales_Channel     9600 non-null   object
 6   Customer_Segment  9653 non-null   object
 7   Age               9851 non-null   object
 8   Category          9696 non-null   object
 9   Subcategory       9543 non-null   object
 10  Quantity          9842 non-null   float64
 11  Unit_Price        9841 non-null   float64
 12  Total_Sales       9890 non-null   float64
 13  Cost              9890 non-null   float64
 14  Profit            9890 non-null   float64
 15  Payment_Method    9499 non-null   object
 16  Satisfaction      9855 non-null   object
 17  Delivery_Date     9713 non-null   object
dtypes: float64(5), object(13)
memory usage: 1.4+ MB

In [6]:
df.isna().sum()

Order_ID              0
Customer_ID           0
Order_Date           33
Region              242
City                343
Sales_Channel       290
Customer_Segment    237
Age                  39
Category            194
Subcategory         347
Quantity             48
Unit_Price           49
Total_Sales           0
Cost                  0
Profit                0
Payment_Method      391
Satisfaction         35
Delivery_Date       177
dtype: int64

In [7]:
df.head()

,Order_ID,Customer_ID,Order_Date,Region,City,Sales_Channel,Customer_Segment,Age,Category,Subcategory,Quantity,Unit_Price,Total_Sales,Cost,Profit,Payment_Method,Satisfaction,Delivery_Date
0,ORD-3908-001887,CUST_00581,2022-10-20,North,Chandigarh,Online,Consumer,42.0,Grocery,Beverages,2.0,1385.54,2771.08,2095.78,675.31,UPI,4.0,2022-10-23
1,ORD-6029-004008,CUST_00028,2022-06-29,South,Bengaluru,Marketplace,Consumer,39.0,Home appliances,Packaged Food,3.0,889.64,2668.92,1300.94,1367.99,UPI,5.0,2022-07-02
2,ORD-5140-003119,CUST_01199,2022-01-31,South,Bengaluru,Marketplace,Corporate,23.0,Office Supplies,Organizers,1.0,1304.85,1304.85,873.57,235.55,Wallet,4.2,2022-02-02
3,ORD-11805-009784,CUST_00734,2023-04-11,Central,Bhopal,Online,Consumer,58.0,Clothing,Footwear,5.0,6614.23,33071.15,13373.58,9776.23,UPI,3.4,2023-04-12
4,ORD-9231-007210,CUST_00499,2023-06-03,West,Mumbai,Phone,Consumer,20.0,electronics,Tables,2.0,39889.20,79778.40,38818.39,36971.09,Credit Card,2.8,2023-06-08

In [8]:
# Handling misleading values
#  text cleaning 

df['Region'].unique()

array(['North', 'South', 'Central', 'West', 'East', nan, 'WEST', 'South ',
       'north', 'south', 'central ', 'NORTH '], dtype=object)

In [9]:
df['Region']=df['Region'].str.title().str.strip()

In [10]:
df['City'].unique()

array(['Chandigarh', 'Bengaluru', 'Bhopal', 'Mumbai', 'Delhi', 'Kolkata',
       'Ahmedabad', 'Guwahati', 'Nagpur', 'Hyderabad', 'Pune', 'Indore',
       'Jaipur', 'Chennai', nan, 'Bhubaneswar'], dtype=object)

In [11]:
df['Sales_Channel'].unique()

array(['Online', 'Marketplace', 'Phone', 'Store', 'E Commerce', nan,
       'market place', 'e-commerce', 'Store ', 'ONLINE', ' online',
       'store'], dtype=object)

In [12]:
df['Sales_Channel'] = df['Sales_Channel'].str.title().str.strip()
df['Sales_Channel']=df['Sales_Channel'].replace("Marketplace","Market Place")
df['Sales_Channel']=df['Sales_Channel'].replace("E Commerce","E-Commerce")

In [13]:
df['Sales_Channel'].unique()

array(['Online', 'Market Place', 'Phone', 'Store', 'E-Commerce', nan],
      dtype=object)

In [14]:
df['Customer_Segment'].unique()

array(['Consumer ', 'Consumer', 'Corporate', 'Small Business', nan,
       'Small business', 'small_business', 'corporate ', 'CORPORATE',
       'consumer'], dtype=object)

In [15]:
df['Customer_Segment']=df['Customer_Segment'].str.strip().str.title()
df['Customer_Segment']=df['Customer_Segment'].replace("Small_Business","Small Business")

In [16]:
df['Customer_Segment'].unique()

array(['Consumer', 'Corporate', 'Small Business', nan], dtype=object)

In [17]:
df['Category'].unique()

array(['Grocery', 'Home appliances', 'Office Supplies', 'Clothing',
       'electronics', 'Sports', 'Home Appliances', 'Electronics', nan,
       'Furniture', 'office supplies', 'Beauty', 'Electronics ',
       'ELECTRONICS', 'Office supplies'], dtype=object)

In [18]:
df['Category']=df['Category'].str.strip().str.title()

In [19]:
df['Category'].unique()

array(['Grocery', 'Home Appliances', 'Office Supplies', 'Clothing',
       'Electronics', 'Sports', nan, 'Furniture', 'Beauty'], dtype=object)

In [20]:
df['Subcategory'].unique()

array(['Beverages', 'Packaged Food', 'Organizers', 'Footwear', 'Tables',
       nan, 'Team Sports', 'Cooling', 'Women', 'Laptops', 'Kids',
       'Binders', 'Chairs', 'Desks', 'Accessories', 'Fitness', 'Cleaning',
       'Pens', 'Phones', 'Personal Care', 'Men', 'Haircare', 'Storage',
       'Paper', 'Audio', 'Snacks', 'Outdoor', 'Cosmetics', 'Staples',
       'Cycling', 'Skincare', 'Small Appliances', 'Kitchen'], dtype=object)

In [21]:
df['Subcategory']=df['Subcategory'].str.strip().str.title()

In [22]:
df['Subcategory'].unique()

array(['Beverages', 'Packaged Food', 'Organizers', 'Footwear', 'Tables',
       nan, 'Team Sports', 'Cooling', 'Women', 'Laptops', 'Kids',
       'Binders', 'Chairs', 'Desks', 'Accessories', 'Fitness', 'Cleaning',
       'Pens', 'Phones', 'Personal Care', 'Men', 'Haircare', 'Storage',
       'Paper', 'Audio', 'Snacks', 'Outdoor', 'Cosmetics', 'Staples',
       'Cycling', 'Skincare', 'Small Appliances', 'Kitchen'], dtype=object)

In [23]:
df['Payment_Method'].unique()

array(['UPI', 'Wallet', 'Credit Card', 'Cash', 'Debit Card',
       'Net Banking', 'Cash ', nan, 'net banking', 'credit_card',
       'NetBanking', 'upi ', 'Credit card'], dtype=object)

In [24]:
df['Payment_Method']=df['Payment_Method'].str.strip().str.title()

In [25]:
df['Payment_Method'].unique()

array(['Upi', 'Wallet', 'Credit Card', 'Cash', 'Debit Card',
       'Net Banking', nan, 'Credit_Card', 'Netbanking'], dtype=object)

In [26]:
df['Payment_Method']=df['Payment_Method'].str.title()
df['Payment_Method']=df['Payment_Method'].replace({"Credit_Card":"Credit Card",
                                                  "Netbanking":"Net Banking"})

In [27]:
df['Payment_Method'].unique()

array(['Upi', 'Wallet', 'Credit Card', 'Cash', 'Debit Card',
       'Net Banking', nan], dtype=object)

In [28]:
df.dtypes

Order_ID             object
Customer_ID          object
Order_Date           object
Region               object
City                 object
Sales_Channel        object
Customer_Segment     object
Age                  object
Category             object
Subcategory          object
Quantity            float64
Unit_Price          float64
Total_Sales         float64
Cost                float64
Profit              float64
Payment_Method       object
Satisfaction         object
Delivery_Date        object
dtype: object

In [29]:
# lets clean nnumerical data

In [30]:
df['Age'].unique()

array(['42.0', '39.0', '23.0', '58.0', '20.0', '36.0', '25.0', '29.0',
       '27.0', '48.0', '34.0', '28.0', '33.0', '50.0', '46.0', '54.0',
       '30.0', '52.0', '37.0', '32.0', '40.0', '43.0', '38.0', '31.0',
       '45.0', '49.0', '51.0', '53.0', '41.0', '21.0', '6.0', '26.0',
       '24.0', '22.0', '55.0', '59.0', '13.0', '15.0', '35.0', '16.0',
       '4.0', '44.0', '14.0', '47.0', '-38.0', '10.0', '60.0', '17.0',
       '62.0', '57.0', '69.0', '56.0', '61.0', '7.0', '67.0', '63.0', '0',
       '19.0', '18.0', '-50.0', nan, '11.0', '-77.0', '3', '-52.0',
       '70.0', '-', '66.0', '5.0', '9.0', '68.0', '8.0', '-34.0', '120',
       '-40.0', '7', '64.0', '12.0', '75.0', '-1.0', '3.0', '2.0',
       '-36.0', '-47.0', '65.0', '-5.0', '74.0', 'not available',
       'unknown', '71.0', '99', '-28.0', 'ERROR', '-6.0', '-44.0',
       '-43.0', '-45.0', '-0.0', '-35.0', '72.0', '-2.0', '1.0', '-46.0',
       '-48.0', '-29.0', '-49.0'], dtype=object)

In [31]:
# lets replace error values and unknown values into null values and remove the negative age

df['Age']=pd.to_numeric(df['Age'],errors='coerce')

In [32]:
# df.loc[df['Age'] < 0] -- to look the negative age rows

In [33]:
df = df.copy()
df = df[(df['Age'] > 0) | (df['Age'].isna())]

In [34]:
df['Age'].unique()

array([ 42.,  39.,  23.,  58.,  20.,  36.,  25.,  29.,  27.,  48.,  34.,
        28.,  33.,  50.,  46.,  54.,  30.,  52.,  37.,  32.,  40.,  43.,
        38.,  31.,  45.,  49.,  51.,  53.,  41.,  21.,   6.,  26.,  24.,
        22.,  55.,  59.,  13.,  15.,  35.,  16.,   4.,  44.,  14.,  47.,
        10.,  60.,  17.,  62.,  57.,  69.,  56.,  61.,   7.,  67.,  63.,
        19.,  18.,  nan,  11.,   3.,  70.,  66.,   5.,   9.,  68.,   8.,
       120.,  64.,  12.,  75.,   2.,  65.,  74.,  71.,  99.,  72.,   1.])

In [35]:
df['Quantity'].unique()

array([  2.,   3.,   1.,   5.,   4.,  10.,   6.,  12.,   8., 100.,  nan,
         0.,  50., 999.])

In [36]:

# df['Quantity'] = pd.to_numeric(df['Quantity'],errors='coerce').astype('Int64')

df = df[(df['Quantity']>0) |  (df['Quantity'].isna())]

In [37]:
df['Quantity'].unique()

array([  2.,   3.,   1.,   5.,   4.,  10.,   6.,  12.,   8., 100.,  nan,
        50., 999.])

In [38]:
df['Satisfaction'].unique()

array(['4.0', '5.0', '4.2', '3.4', '2.8', '3.6', '3.7', '3.9', '4.5',
       '2.5', '4.4', '4.1', '4.7', '4.9', '3.1', '-4.8', '3.2', '4.3',
       '3.3', '2.3', '2.9', 'unknown', '3.8', '2.0', '4.6', '1.8', '-3.0',
       '2.4', '2.2', '3.5', '4.8', '3.0', '2.1', '2.7', '1.9', '1.1',
       '2.6', '0', nan, '-3.4', '-3.6', '6', '1.6', '99', '1.3', '-3.3',
       '1.7', '1.5', 'ERROR', '-', '1.4', 'not available', '0.0', '-2.7',
       '-4.4', '8', '-2.6', '8.0', '-4.6', '-4.9', '-3.2', '-3.9', '-4.5',
       '-3.1', '-5.0'], dtype=object)

In [39]:
df['Satisfaction']=pd.to_numeric(df['Satisfaction'],errors='coerce')

In [40]:
df['Satisfaction'].unique()

array([ 4. ,  5. ,  4.2,  3.4,  2.8,  3.6,  3.7,  3.9,  4.5,  2.5,  4.4,
        4.1,  4.7,  4.9,  3.1, -4.8,  3.2,  4.3,  3.3,  2.3,  2.9,  nan,
        3.8,  2. ,  4.6,  1.8, -3. ,  2.4,  2.2,  3.5,  4.8,  3. ,  2.1,
        2.7,  1.9,  1.1,  2.6,  0. , -3.4, -3.6,  6. ,  1.6, 99. ,  1.3,
       -3.3,  1.7,  1.5,  1.4, -2.7, -4.4,  8. , -2.6, -4.6, -4.9, -3.2,
       -3.9, -4.5, -3.1, -5. ])

In [41]:
# df.loc[(df['Satisfaction']<0) | (df['Satisfaction']>5)]

In [42]:
df.loc[(df['Satisfaction']<1) | (df['Satisfaction']>5), 'Satisfaction']=np.nan

In [43]:
df.isna().sum()

Order_ID              0
Customer_ID           0
Order_Date           33
Region              242
City                343
Sales_Channel       290
Customer_Segment    236
Age                  55
Category            193
Subcategory         339
Quantity             48
Unit_Price           49
Total_Sales           0
Cost                  0
Profit                0
Payment_Method      388
Satisfaction        117
Delivery_Date       175
dtype: int64

In [44]:
# filling null values

df['Order_Date']=df['Order_Date'].fillna(df['Order_Date'].mode()[0])

In [45]:
df['Region']=df['Region'].fillna(df['Region'].mode()[0])

In [46]:
df['Sales_Channel']=df['Sales_Channel'].fillna(df['Sales_Channel'].mode()[0])

In [47]:
df['Customer_Segment']=df['Customer_Segment'].fillna(df['Customer_Segment'].mode()[0])

In [48]:
df['Age']=df['Age'].fillna(df['Age'].median())

In [49]:
df['Category']=df['Category'].fillna(df['Category'].mode()[0])

In [50]:
df['Subcategory']=df['Subcategory'].fillna(df['Subcategory'].mode()[0])

In [51]:
df['Age']=df['Age'].fillna(df['Age'].median())

In [52]:
# df.loc[df['Quantity'].isna()]

In [54]:
df['Quantity'] = df['Quantity'].fillna( df['Total_Sales'] / df['Unit_Price']).round().astype('Int64')

# df['Quantity'] = pd.to_numeric(df['Quantity'],errors='coerce').astype('Int64')

In [55]:
#  df.loc[df['Unit_Price'].isna()] 
#     to check the null values in unit price

In [56]:
df['Unit_Price'] = df['Unit_Price'].fillna( df['Total_Sales'] / df['Quantity'])

In [57]:
df['Payment_Method']=df['Payment_Method'].fillna(df['Payment_Method'].mode()[0])

In [58]:
df['Satisfaction']=df['Satisfaction'].fillna(df['Satisfaction'].median())

In [59]:
df['Delivery_Date']=df['Delivery_Date'].fillna(df['Delivery_Date'].mode()[0])

In [60]:
df=df.dropna()

In [61]:
df.describe(include='all')

,Order_ID,Customer_ID,Order_Date,Region,City,Sales_Channel,Customer_Segment,Age,Category,Subcategory,Quantity,Unit_Price,Total_Sales,Cost,Profit,Payment_Method,Satisfaction,Delivery_Date
count,9477,9477,9477,9477,9477,9477,9477,9477.000000,9477,9477,9477.0,9477.0,9.477000e+03,9477.000000,9477.000000,9477,9477.000000,9477
unique,9477,1214,1278,5,15,5,3,NaN,8,32,<NA>,<NA>,NaN,NaN,NaN,6,NaN,1282
top,ORD-3908-001887,CUST_00725,2023-05-05,South,Bengaluru,Online,Consumer,NaN,Electronics,Snacks,<NA>,<NA>,NaN,NaN,NaN,Upi,NaN,2025-06-14
freq,1,21,50,2292,730,4661,5495,NaN,1667,722,<NA>,<NA>,NaN,NaN,NaN,3094,NaN,192
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.004959,NaN,NaN,4.342936,15797.987492,7.179566e+04,33420.026927,15911.849192,NaN,3.774285,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.166365,NaN,NaN,25.357926,34471.825384,6.558105e+05,60581.399814,31549.023204,NaN,0.741004,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,1.0,0.0,0.000000e+00,12.000000,7.090000,NaN,1.100000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.000000,NaN,NaN,2.0,1678.97,4.328760e+03,2627.590000,1118.730000,NaN,3.300000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.000000,NaN,NaN,3.0,6060.9,1.644774e+04,9929.680000,4424.970000,NaN,3.800000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.000000,NaN,NaN,5.0,22607.36,6.058770e+04,36694.800000,16267.980000,NaN,4.300000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.000000,NaN,NaN,999.0,2053172.0,4.490045e+07,719673.390000,449322.220000,NaN,5.000000,NaN

In [62]:
df.reset_index(drop=True, inplace=True)

In [63]:
df.to_csv("cleaned_data.csv",index=False)